### ISSUE TITLE
Missing decorators in example

### ISSUE THREAD

**Issue by sdiop** [jonghwanhyeon/python-ffmpeg#15]
when trying to execute the decorator code in the provided example, I get the below error.  Searching the code did the reveal the definition of the on decorator function either.

AttributeError                            Traceback (most recent call last)
Cell In [9], line 23
      8 import ffmpeg
     11 ffmpegz0 = (FFmpeg()
     12 .option('y')
     13 .input(iz)
   (...)
     20         )
     21 )
---> 23 @ffmpeg.on('start')
     24 def on_start(arguments):
     25         t0 = time.perf_counter()
     26         print(f'started at {datetime.now()}')

AttributeError: module 'ffmpeg' has no attribute 'on'

**Comment by jonghwanhyeon** [comment]
You have to import `FFmpeg` class as below:

```python
from ffmpeg import FFmpeg

ffmpeg = FFmpeg().option('y').input(
    'rtsp://example.com/cam',
    # Specify file options using kwargs
    rtsp_transport='tcp',
    rtsp_flags='prefer_tcp',
).output(
    'output.ts',
    # Use a dictionary when an option name contains special characters
    {'codec:v': 'copy'},
    f='mpegts',
)

@ffmpeg.on('start')
def on_start(arguments):
    print('Arguments:', arguments)
```

**Comment by sdiop** [comment]
@jonghwanhyeon  correct. 
there were a name collusion with another package that caused this.  If you take a quick look you will see that both have the same root folder name and that lead to both packages installed in the same folder leading to the collusion.
https://github.com/jonghwanhyeon/python-ffmpeg
https://github.com/kkroening/ffmpeg-python

After I deleted the ffmpeg-python package, the examples started to work.

May I suggest a renaming of the root folder to reflect the package name and avoid such possibilities of collusion?

Thank you sir for your prompt reply
