### ISSUE TITLE
what's the difference to https://github.com/kkroening/ffmpeg-python

### ISSUE THREAD

**Issue by liudonghua123** [jonghwanhyeon/python-ffmpeg#16]
Hi, I tried to find some python package for using ffmpeg, then I found this one and https://github.com/kkroening/ffmpeg-python, so I am curious about what's the difference between both of them. What's the pros and cons?

And it's seems there is no other language interface recommendation offcially like imagemagick, https://imagemagick.org/script/develop.php#python.

**Comment by jonghwanhyeon** [comment]
This library supports `asyncio`. That's all. If you don't use `asyncio`, it would be better to use `ffmpeg-python` rather than this library.
