### ISSUE TITLE
Also handle stdout

### ISSUE THREAD

**Issue by C0D3D3V** [jonghwanhyeon/python-ffmpeg#17]
Would be nice if we could also handle stdout so I could e.g. "misuse" this lib for ffprobe, because ffprobe uses  stdout instead of stderr.

Example command:
`ffprobe -v error -select_streams v:0 -show_entries stream=width,height,duration -of json -i /path/to/video.mp4`
This prints width, height, duration information in json format to stout

**Comment by jonghwanhyeon** [comment]
As v2.0.0, you can retrieve `stdout`.
