### ISSUE TITLE
Can we use python ffmeg to access windows web cam and save image as jpeg or png?

### ISSUE THREAD

**Issue by mai1x9** [jonghwanhyeon/python-ffmpeg#18]
Can we use this library to access webcam and save as image? From ffmpeg python example, it's possible to access Face Time in Mac Osx as input for ffmeg(https://github.com/kkroening/ffmpeg-python/blob/master/examples/facetime.py) as mentioned in the link ? How about in windows ?

**Comment by jonghwanhyeon** [comment]
Please refer to this document: https://trac.ffmpeg.org/wiki/Capture/Webcam
