### ISSUE TITLE
PytestUnknownMarkWarning: Unknown pytest.mark.asyncio

### ISSUE THREAD

**Issue by xiota** [jonghwanhyeon/python-ffmpeg#21]
After installing, when running `pytests` in the `tests` directory, I get several warning messages stating:

> PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html

To prevent this warning, a file `pytest.ini` file is needed in the `tests` directory with the following contents:
````
[pytest]
markers =
    asyncio: asyncio mark
````

**Comment by jonghwanhyeon** [comment]
Fixed with commit a672c89477f4be8c933dbb8ca5d98c333c16a3b6 🙏
