### ISSUE TITLE
Is there a way to support by a donation/buymeacoffee ?

### ISSUE THREAD

**Issue by symonenkob** [jonghwanhyeon/python-ffmpeg#23]
The ease of adding this lib to a project and progress tracking are awesome! I am not using it in a commercial projects yet, but it looks really promising.
Is there a way to support you somehow, maybe a https://www.buymeacoffee.com/ link?

**Comment by jonghwanhyeon** [comment]
Thank you very much for your generous offer to support the project. However, at this time, I would kindly decline any financial assistance for the project.
