### ISSUE TITLE
SRT Subtitles with pyton-ffmpeg

### ISSUE THREAD

**Issue by EliasLumer** [jonghwanhyeon/python-ffmpeg#27]
I am trying to use your wrapper to input a .webm video, as well as hardburn .srt subtitles onto the video (force_style=Alignment=6, Fontsize=48, Outline=5, Shadow=1, Fontname='KOMIKAX')

Is this possible with your wrapper?

**Comment by jonghwanhyeon** [comment]
If your task can be done using `ffmpeg`, it can also be done using this wrapper. 

According to [the document](https://trac.ffmpeg.org/wiki/HowToBurnSubtitlesIntoVideo),
```python
ffmpeg = (
    FFmpeg()
    .option("y")
    .input("input.mp4")
    .output(
        "ouptut.mp4",
        vf="subtitles=subtitle.srt",
    )
)

**Comment by EliasLumer** [comment]
Ah great -- would you know how to change the font to a specified font in my directory? and the font color?
