### ISSUE TITLE
TypeError: 'ABCMeta' object is not subscriptable

### ISSUE THREAD

**Issue by C0D3D3V** [jonghwanhyeon/python-ffmpeg#28]
Hey :)

one of my users reported an error. I have today no time to test it myself, but since I saw similar errors already I think it is legit. 

https://github.com/C0D3D3V/bbb-dl/issues/40

I saw similar errors with Python 3.8, I think Python 3.8 is more strict about function headers, decorators and type declarations. Funny is that 3.10 is less strict, and often runs the same code without problems. 

But thats only a guess, maybe you have time to investigate or an idea what is going wrong. 

Thank you for your great work :)

**Comment by jonghwanhyeon** [comment]
Thanks for reporting this issue! I fixed it on v2.0.4 😅

**Comment by C0D3D3V** [comment]
Thank you very much ❤
