### ISSUE TITLE
`FFmpegError(f"Non-zero exit status")` hard to debug

### ISSUE THREAD

**Issue by Ben-Brady** [jonghwanhyeon/python-ffmpeg#31]
Right now when ffmpeg fails to execute a generic FFmpegError is raised, it would be nice if if there was some way to inspect the stderr to see what went wrong. Right now my current workaround is to build in the command using `ffmpeg._executable + " ".join(ffmpeg._options.build())` in order to debug these issues. Maybe attaching the `stderr` to the FFmpegError could work?

**Comment by jonghwanhyeon** [comment]
Can you give me some examples of error messages? If possible, I would like to capture error messages rather than reporting stderr lines.

**Comment by Ben-Brady** [comment]
If you set `-loglevel 16` on ffmpeg you only get the final error if there is one, you could use that to extract the error messages.

```bash
ben@slate:~$ ffmpeg -loglevel 16 -i /tmp/tmp5i24dg93 -f mp4 -c:v lib264 -preset fast -crf 21 -c:a libopus -b:a 32000 -y
/tmp/tmpimp71p9
Unknown encoder 'lib264'
ben@slate:~$ ffmpeg -loglevel 16 -i /tmp/tmp5i24dg93 -f mp4 -c:v libx264 -preset fast -crf 21 -c:a libopus -b:a 32000 -y /tmp/tmpimp71p9
ben@slate:~$
```

Also for errors you could have,
- `/tmp/tmp5i24dg9: No such file or directory`
- `Unknown encoder 'lib264x'`
- `File '/tmp/tmpimp71p9' already exists. Exiting.`
- `Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height`

**Comment by Ben-Brady** [comment]
I recon splitting it into `FFmpegSyntaxError`, `FFmpegRuntimeError` with them both inheriting `FFmpegError` (to not break compatibility) would be a good solution.
`FFmpegSyntaxError` would be for commands that would never work because their parameters are incorrect
`FFmpegRuntimeError` would be for commands that failed due to conditions such as an invalid file or already existing files

However, the easiest patch to implement right now would be to populate the `FMpegError` with the error message from -loglevel 16. I'll work on a pull request to do that in a bit.

**Comment by baltic-tea** [comment]
Yes, such an exception often appears and its text is uninformative.
For example, you can get it when trying to extract cover art from an audio file:

```bash
ffmpeg -y -i input_audio.flac output_image.jpg
```

```python
import asyncio
from ffmpeg.asyncio import FFmpeg

def extract_thumb() -> bytes:
    return await (
        FFmpeg()
        .option("y")
        .input("./input_audio.flac")
        .output("pipe:1.jpg", options)
        .execute()
    )
    
b_thumb = asyncio.run(extract_thumb())
```

**Comment by electrotechtom** [comment]
> I recon splitting it into `FFmpegSyntaxError`, `FFmpegRuntimeError` with them both inheriting `FFmpegError` (to not break compatibility) would be a good solution. `FFmpegSyntaxError` would be for commands that would never work because their parameters are incorrect `FFmpegRuntimeError` would be for commands that failed due to conditions such as an invalid file or already existing files
> 
> However, the easiest patch to implement right now would be to populate the `FMpegError` with the error message from -loglevel 16. I'll work on a pull request to do that in a bit.

I'd agree with this. I've just spent a lot of time trying to debug undifferentiated FFmpegError exceptions: in the end I had to walk through with pdb to get the arguments passed to ffmpeg and copy-paste the same argument string directly to ffmpeg on the command-line to see its output.
