### ISSUE TITLE
Excuse me. I want to get the video duration, how do I get it.

### ISSUE THREAD

**Issue by WytheLi** [jonghwanhyeon/python-ffmpeg#33]
Excuse me. I want to get the video duration, how do I get it.

**Comment by golyalpha** [comment]
You need to use `ffprobe` for that.

If you don't want to be grabbing another library, you could abuse this one's custom executable mechanism something like this:
```py
ffprobe = (
    FFmpeg("ffprobe")
    .option("hide_banner")
    .option("show_format")
    .option("show_streams")
    .option("of", "json")
    .option("count_packets")
    .input(source)
)
```

You could then `await ffprobe.execute()` and `json.loads` the result (assuming you're using the async variant, sync doesn't need await). 

Out you'll get a dict containing all the streams in the file, and specifically for video streams, `nb_packet_count` is usually (yet to see a file where that wasn't the case) the number of frames in the stream. Combine that with framerate, and you get runtime of the stream in seconds.

Depending on your source file, the length of the video may be obtained some other way, but `nb_packet_count` seems to work fairly universally. Do keep in mind however, that it does make `ffprobe` read the entire file to actually count the packets - if you don't want and don't need that, you can remove the `count_packets` option and use an alternative key within the dict. If instead you find that the `nb_packet_count` is not accurate, you can use `count_frames` instead - unfortunately that will be even slower, as ffprobe then has to actually decode the video stream and count the frames inside it.

**Comment by jonghwanhyeon** [comment]
As @golyalpha said, we can employ `ffprobe` for your purpose. Please refer to https://python-ffmpeg.readthedocs.io/en/latest/examples/querying-metadata/
