### ISSUE TITLE
invalid literal for int() with base 10: '0KiB'

### ISSUE THREAD

**Issue by C0D3D3V** [jonghwanhyeon/python-ffmpeg#53]
I have not yet tested it. But one of my users reported the error: `invalid literal for int() with base 10: '0KiB'`

I guess in the latest version, the parsing of the status line got broken, since you now also allow parsing of audio encoding status. 

I will test it in the next days myself, and see if I can find a solution.

**Comment by C0D3D3V** [comment]
I tried to reproduce the error. But I can not, on linux. I guess it is a Windows bug. If I can reproduce the bug, I will repoen the issue.

**Comment by C0D3D3V** [comment]
I tested it on Windows, there it crashes on a status line that looks like this: `frame=  133 fps= 26 q=28.0 size=       0KiB time=00:00:05.37 bitrate=   0.1kbits/s dup=541 drop=0 speed=1.04x`

**Comment by C0D3D3V** [comment]
The error was introduced in v2.0.3, v2.0.2 is working fine on windows (but just does not emit any status). 

The problem is this line `"size": lambda item: int(item.replace("kB", "")) * 1024,`  because size is  `0KiB` and not `0kB`

**Comment by jonghwanhyeon** [comment]
Resolved #51
