### ISSUE TITLE
Why "await ffmpeg.execute()"  doesnt work in async function?

### ISSUE THREAD

**Issue by zhouwe1** [jonghwanhyeon/python-ffmpeg#54]
`Traceback (most recent call last):
  File "/utils.py", line 108, in get_screenshot
    await ffmpeg.execute()
TypeError: object bytes can't be used in 'await' expression`

**Comment by chadawagner** [comment]
Sounds like you're maybe not importing from `ffmpeg.asyncio`? See the [asyncio examples](https://github.com/jonghwanhyeon/python-ffmpeg/tree/main/examples/asyncio)

**Comment by zhouwe1** [comment]
Yes, I made a mistake. Thank you very much!
