### ISSUE TITLE
pyee: RuntimeWarning: coroutine 'on_start/on_stderr/on_progress' was never awaited

### ISSUE THREAD

**Issue by gagantk** [jonghwanhyeon/python-ffmpeg#8]
I am using this python module since months. There was never an issue with this.
Upon updating the **pyee** module which was released this month, I'm starting to get these warnings `RuntimeWarning: coroutine 'on_start/on_stderr/on_progress' was never awaited` and the process stops.

I checked by degrading the pyee module to 7.0.2 and it works fine now. A fix is required for python-ffmpeg to work with changes in pyee.

**Comment by jonghwanhyeon** [comment]
It seems resolved issue!
