### ISSUE TITLE
ImportError: cannot import name 'FFmpeg'

### ISSUE THREAD

**Issue by hcw1202** [jonghwanhyeon/python-ffmpeg#9]
`from ffmpeg import FFmpeg`
result
`ImportError: cannot import name 'FFmpeg'`

**Comment by pinakee** [comment]
Try 'from ffmpeg.ffmpeg import FFmpeg'

**Comment by Mojken** [comment]
That doesn't work either. Why is this even an issue? This is just lack of competence.

**Comment by RandomMurican** [comment]
> That doesn't work either. Why is this even an issue? This is just lack of competence.

Did you install the right ffmpeg? The Py2 version gives the reported error.

**Comment by ewerybody** [comment]
cannot repro. Importing works just fine.

**Comment by Happylama25** [comment]
Had the same issue, restarting my IDE and importing as 'from ffmpeg.ffmpeg import FFmpeg' worked, without the added .ffmpeg it didnt.
